### ISSUE TITLE
게시판 1개가 신청되면 이후 다른 게시판 신청이 안됩니다.

### ISSUE THREAD

**Issue by wookho** [ForPeople/GGNewsletter#4]
이미 신청한 이메일로 다른 게시판 신청시 친청이 등록되지 않습니다.

위젯 코드 생성시 각 게시판을 따로 대상으로 선정하고 위젯 코드를 각 게시판마다 다르게 해서 설치했습니다.
관리자페이지에 가서 보면 맨 처음 등록한 모듈번호로 등록이 되어 있습니다.

**Comment by wookho** [comment]
일단 php 코드에서 보니 이메일 중복 체크하는 부분 이 있어서
 		$obj->ggmailing_email`` = Context::get('email_address');
			$obj->ggmailing_module_srl = $args->module_srl; // 모듈번호 세팅하는 부분을 추가
			$output = executeQueryArray('ggmailing.getBoardMember',$obj); // 중복 이메일 체크




모듈번호 세팅하는 부분을 추가해 주니 잘 되는 것 같습니다.

**Comment by ForPeople** [comment]
오옷... 이곳에 이슈 댓글이 달리다니~
소중한 피드백 감사합니다.

**Comment by ForPeople** [comment]
https://github.com/ForPeople/GGNewsletter/commit/86eb66230a15613bde1c0953d6095e8919eb9187
