### ISSUE TITLE
이메일 체크 부분에  id 부분  .(dot) 사용 가능하도록 

### ISSUE THREAD

**Issue by wookho** [ForPeople/GGNewsletter#5]
이부분에 문의가 들어왔습니다. 
https://rxtip.kr/rx_tip/1447

이슈로 요청하셔서 등록합니다.

**Comment by ForPeople** [comment]
https://github.com/ForPeople/GGNewsletter/commit/cafb4be8e493993c795036c78ad71ac0023ae635
