### ISSUE TITLE
이메일 체크 새 정규식 반영시 문제

### ISSUE THREAD

**Issue by wookho** [ForPeople/GGNewsletter#6]
조건문 문제는 아닌거 같고 일단 새로운 정규식 적용했는데 

id에 . 가 들어가면 통과되지 못하네요.

. 와 상관없이 통과가 못하는 거네요.

**Comment by ForPeople** [comment]
https://github.com/ForPeople/GGNewsletter/commit/c008fab66d699785362b6063c8866fb9bffe3530

다시 한번 해보시겠어요?

**Comment by ForPeople** [comment]
https://github.com/ForPeople/GGNewsletter/commit/7215d971ea09b57f9982279dc85e73d7a8320897
이게 더 좋아 보이네요 👍

**Comment by wookho** [comment]
@ForPeople  이메일 주소 입력후 버튼 누르면 스크립트 에러가 발생하네요.
Uncaught ReferenceError: preg_match is not defined

    at ggnewsletter_check ((index):463)
    at ggnewsletter_submit ((index):448)
    at HTMLInputElement.onclick ((index):442)

**Comment by wookho** [comment]
@ForPeople

https://github.com/ForPeople/GGNewsletter/commit/7215d971ea09b57f9982279dc85e73d7a8320897

이거 해보겠습니다.

**Comment by wookho** [comment]
역시 스크립트 에러가 나네요. 이메일 주소 넣고 버튼 누르면 발생합니다.
(index):462 Uncaught ReferenceError: filter_var is not defined
    at ggnewsletter_check ((index):462)
    at ggnewsletter_submit ((index):448)
    at HTMLInputElement.onclick ((index):442)

**Comment by ForPeople** [comment]
제가 요즘 정신이 오락가락 하나 봅니다.
자바스크립트에 php 함수를 넣고 있다니...

https://github.com/ForPeople/GGNewsletter/commit/c3c7eb257ac5ce02c2cabdfab19069e2d4f96deb

죄송합니다.

**Comment by wookho** [comment]
https://github.com/ForPeople/GGNewsletter/commit/c3c7eb257ac5ce02c2cabdfab19069e2d4f96deb

위 정규식도 이상하게 어떤 이메일도 통과를 못합니다.

제가 처음 제안한 정규식도 설명한 사이트 페이지에서는 이상이 없이 테스트가 되었거든요.
https://webisfree.com/2016-05-12/%EC%9D%B4%EB%A9%94%EC%9D%BC-%EC%A3%BC%EC%86%8C-%EA%B2%80%EC%A6%9D-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D

여기서 테스트해보시면 잘되니다.

그런데 저희 스킨에 넣으면 안되는 상황이죠.

**Comment by ForPeople** [comment]
번거롭게 해드려서 죄송합니다.
제가 다시 한번 테스트 해보도록 하겠습니다.

**Comment by ForPeople** [comment]
https://github.com/ForPeople/GGNewsletter/commit/3a02ea38a594f597b41a7a2e0e87c8b824d8c816

테스트도 해 보았습니다.

**Comment by wookho** [comment]
https://github.com/ForPeople/GGNewsletter/commit/3a02ea38a594f597b41a7a2e0e87c8b824d8c816

요것 잘되네요. 감사합니다.

**Comment by ForPeople** [comment]
도와 주셔서 감사드려요~ 이슈 클로즈!
